# E4 C2 Backend gitlab ci file

image: golang:1.12

stages:
  - build-docker


before_script:
  # Packages
  - PACKAGES="bash"
  - command -v apt >/dev/null 2>&1 && (apt-get update && apt-get install -y ${PACKAGES}) || (apk update && apk add ${PACKAGES})


build-docker:
  image: docker:stable
  stage: build-docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./scripts/docker-build.sh
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.gitlab.com/teserakt/e4/webui:${CI_COMMIT_REF_NAME//\//_}
    - docker push registry.gitlab.com/teserakt/e4/webui:${CI_COMMIT_SHORT_SHA}
